version: '3.8'

services:
  # Existing services
  hello:
    image: 'hello-world'
    restart: "no"
  
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  
  # Skyvern services
  postgres:
    image: postgres:14-alpine
    user: "1000:1000"  # Use a non-root user to avoid permission issues
    restart: unless-stopped
    # comment out if you want to externally connect DB
    # ports:
    #   - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: skyvern
      POSTGRES_PASSWORD: skyvern
      POSTGRES_DB: skyvern  # Fixed typo in variable name
      # Performance tuning parameters
      POSTGRES_SHARED_BUFFERS: 128MB  # 25% of available RAM for small instances
      POSTGRES_EFFECTIVE_CACHE_SIZE: 384MB  # 75% of available RAM for small instances
      POSTGRES_WORK_MEM: 4MB  # Reasonable default for small instances
      POSTGRES_MAINTENANCE_WORK_MEM: 32MB  # For maintenance operations
      POSTGRES_MAX_CONNECTIONS: 100  # Default is usually fine for small instances
      # Logging parameters
      POSTGRES_LOG_MIN_DURATION_STATEMENT: 250  # Log slow queries (>250ms)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skyvern"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s  # Give PostgreSQL time to start up
    networks:
      - app-network

  skyvern:
    image: public.ecr.aws/skyvern/skyvern:latest
    restart: on-failure
    # comment out if you want to externally call skyvern API
    ports:
      - 8000:8000
    volumes:
      - ./artifacts:/data/artifacts
      - ./videos:/data/videos
      - ./har:/data/har
      - ./log:/data/log
      - ./.streamlit:/app/.streamlit
    environment:
      - DATABASE_STRING=postgresql+psycopg://skyvern:skyvern@postgres:5432/skyvern?sslmode=disable
      - BROWSER_TYPE=chromium-headful
      - ENABLE_OPENAI=true
      - LLM_KEY=OPENAI_GPT4O
      - OPENAI_API_KEY=<your_openai_key>
      # If you want to use other LLM provider, like azure and anthropic:
      # - ENABLE_ANTHROPIC=true
      # - LLM_KEY=ANTHROPIC_CLAUDE3.5_SONNET
      # - ANTHROPIC_API_KEY=<your_anthropic_key>
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "test", "-f", "/app/.streamlit/secrets.toml"]
      interval: 5s
      timeout: 5s
      retries: 5

  skyvern-ui:
    image: public.ecr.aws/skyvern/skyvern-ui:latest
    restart: on-failure
    ports:
      - 8080:8080
      - 9090:9090
    volumes:
      - ./artifacts:/data/artifacts
      - ./videos:/data/videos
      - ./har:/data/har
      - ./.streamlit:/app/.streamlit
    environment:
      - VITE_WSS_BASE_URL=ws://localhost:8000/api/v1
    depends_on:
      skyvern:
        condition: service_healthy
    networks:
      - app-network

  # Playwright automation service
  playwright:
    image: mcr.microsoft.com/playwright:v1.42.1-focal
    restart: unless-stopped
    volumes:
      - ./src:/app
      - ./artifacts:/app/artifacts
      - ./videos:/app/videos
      - ./har:/app/har
      - ./log:/app/log
    working_dir: /app
    environment:
      - NODE_ENV=development
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
      - SKYVERN_API_URL=http://skyvern:8000
      - SKYVERN_UI_URL=http://skyvern-ui:8080
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      skyvern:
        condition: service_healthy
      skyvern-ui:
        condition: service_started
    command: bash -c "cd /app && chmod +x install-dependencies.sh && ./install-dependencies.sh && tail -f /dev/null"  # Install dependencies and keep container running
    networks:
      - app-network

  # Express.js backend API service
  backend-api:
    image: node:18-alpine
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
      - ./artifacts:/app/artifacts
      - ./videos:/app/videos
      - ./har:/app/har
      - ./log:/app/log
    working_dir: /app
    environment:
      - NODE_ENV=development
      - PORT=8000
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
      - SKYVERN_API_URL=http://skyvern:8000
      - SKYVERN_UI_URL=http://skyvern-ui:8080
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key}
      # Database connection environment variables
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=skyvern
      - DB_USER=skyvern
      - DB_PASSWORD=skyvern
    depends_on:
      - playwright
      - skyvern
    command: sh -c "chmod +x install-backend-dependencies.sh && ./install-backend-dependencies.sh && npm start"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/api/status"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  # LangChain AI service
  langchain-js:
    image: mcr.microsoft.com/playwright:v1.42.1-focal
    # Using Playwright image as base for Node.js
    restart: unless-stopped
    volumes:
      - ./src:/app
      - ./artifacts:/app/artifacts
      - ./log:/app/log
    working_dir: /app
    environment:
      - NODE_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key}
      - SKYVERN_API_URL=http://skyvern:8000
      - SKYVERN_UI_URL=http://skyvern-ui:8080
    depends_on:
      skyvern:
        condition: service_healthy
    command: bash -c "cd /app && chmod +x install-dependencies.sh && ./install-dependencies.sh && tail -f /dev/null"  # Install dependencies and keep container running
    networks:
      - app-network

  # LangChain Python service
  langchain-py:
    image: python:3.10-slim
    restart: unless-stopped
    volumes:
      - ./src:/app
      - ./artifacts:/app/artifacts
      - ./log:/app/log
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key}
      - SKYVERN_API_URL=http://skyvern:8000
      - SKYVERN_UI_URL=http://skyvern-ui:8080
    depends_on:
      skyvern:
        condition: service_healthy
    # Install Python dependencies and keep container running
    command: bash -c "pip install -U langchain langchain-openai playwright && python -m playwright install && tail -f /dev/null"
    networks:
      - app-network

  # Terminal-themed React Web UI for authentication
  webui:
    build:
      context: ./src/webui
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./src/webui:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:8000/api
      - REACT_APP_WS_HOST=localhost:8000
    depends_on:
      - backend-api
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

volumes:
  postgres_data:
    # Using a named volume instead of a bind mount to avoid permission issues
    # This ensures data persistence across container restarts and rebuilds

networks:
  app-network:
    driver: bridge