[skyvern]
configs = [
    {"env" = "local", "host" = "http://skyvern:8000/api/v1", "orgs" = [{name="Skyvern", cred="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ4ODY5MjM1NDAsInN1YiI6Im9fMzcwNTcxMjM1NTI0MDg5Nzc4In0.3oJrH-OmL6G-yf7LE7XuSf5U-ItfWAxhOmWuLUbCCpw"}]}
]
